#Image
image:
  repository: "844586871941.dkr.ecr.us-east-1.amazonaws.com/ecom-ecr"
  tag: "product-service-c5a554f759b25945821689e93090e2ec27fe9ca0"
  pullPolicy: IfNotPresent

#Replicas
replicas: 2

#Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

#HPA
hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPU: 70

#Non-sensitive config
config:
  dbName: "product_db"
  authServiceUrl: "http://auth-stable:8000"
  useS3: "true"
  s3BucketName: "<output from terraform>"
  awsRegion: "us-east-1"
  


#Service account
serviceAccountName: backend-sa


#Port
port: 8000
