apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cart-rollout
  labels:
    app.kubernetes.io/name: cart-svc
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cart-app
  strategy:
    canary:
      stableService: cart-stable
      canaryService: cart-canary
      trafficRouting:
        alb:
          ingress: alb-ingress
          servicePort: {{ .Values.port }}
      steps:
        - setWeight: 10
        - pause:
            duration: 2m
        - setWeight: 50
        - pause:
            duration: 2m
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: backend-db-secrets
      containers:
        - name: cart-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          env:
            - name: DB_NAME
              value: {{ .Values.config.dbName | quote }}

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: port
            
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.config.kafkaBootstrapServers | quote }}
            - name: AUTH_SERVICE_URL
              value: {{ .Values.config.authServiceUrl | quote }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}