apiVersion: v1
kind: Service
metadata:
  name: cart-stable
spec:
  type: ClusterIP
  selector:
    app: cart-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: cart-canary
spec:
  type: ClusterIP
  selector:
    app: cart-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}