apiVersion: v1
kind: Service
metadata:
  name: order-stable
spec:
  type: ClusterIP
  selector:
    app: order-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: order-canary
spec:
  type: ClusterIP
  selector:
    app: order-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}