#Image
image:
  repository: "844586871941.dkr.ecr.us-east-1.amazonaws.com/ecom-ecr"
  tag: "order-service-ac1cd36808e655800f62821b9362ec88ab2a7328"
  pullPolicy: IfNotPresent

#Replicas
replicas: 2

#Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

#HPA
hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPU: 70

#Non-sensitive config
config:
  dbName: "order_db"
  kafkaBootstrapServers: "kafka-kafka-bootstrap.default.svc.cluster.local:9092"
  authServiceUrl: "http://auth-stable:8000"
  cartServiceUrl: "http://cart-stable:8000"

#App secrets
appSecrets:
  secretKey: ""


#Service account
serviceAccountName: backend-sa


#Port
port: 8000
