apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-stable
                port:
                  number: {{ .Values.backendPort }}
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: product-stable
                port:
                  number: {{ .Values.backendPort }}
          - path: /api/cart
            pathType: Prefix
            backend:
              service:
                name: cart-stable
                port:
                  number: {{ .Values.backendPort }}
          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: order-stable
                port:
                  number: {{ .Values.backendPort }}
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: payment-stable
                port:
                  number: {{ .Values.backendPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: {{ .Values.frontendPort }}