import api from '@/utils/axios'
import type { Product } from '@/types'

export const getProducts = async (): Promise<Product[]> => {
    const response = await api.get('/api/products/')
    return response.data
}

export const getProduct = async (id: number): Promise<Product> => {
    const response = await api.get(`/api/products/${id}`)
    return response.data
}

export const createProduct = async (data: Omit<Product, 'id'>): Promise<Product> => { //We use Omit here to omit id from payload. id is generated by backend.
    const response = await api.post('/api/products/', data)
    return response.data
}

export const updateProduct = async (id: number, data: Omit<Product, 'id'>): Promise<Product> => { //We also use Omit here to omit id from payload since we're requesting to update the product info minus the id.
    const response = await api.put(`/api/products/${id}`, data)
    return response.data
}

export const deleteProduct = async (id: number): Promise<void> => {
    await api.delete(`/api/products/${id}`)
}