apiVersion: v1
kind: Secret
metadata:
  name: product-app-secret
  labels:
    app.kubernetes.io/name: product-svc
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.appSecrets.secretKey | required "appSecrets.secretKey is required" | quote }}