apiVersion: v1
kind: Service
metadata:
  name: product-stable
spec:
  type: ClusterIP
  selector:
    app: product-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: product-canary
spec:
  type: ClusterIP
  selector:
    app: product-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}