apiVersion: v1
kind: Service
metadata:
  name: payment-stable
spec:
  type: ClusterIP
  selector:
    app: payment-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-canary
spec:
  type: ClusterIP
  selector:
    app: payment-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}