#Image
image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

#Replicas
replicas: 2

#Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

#HPA
hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPU: 70

#Non-sensitive config
config:
  dbName: "payment_db"
  kafkaBootstrapServers: "kafka.default.svc.cluster.local:9092"
  authServiceUrl: "http://auth-stable:8000"
  orderServiceUrl: "http://order-stable:8000"

#App secrets
appSecrets:
  stripeSecretKey: ""
  stripeWebhookSecret: ""


#Service account
serviceAccountName: backend-sa


#Port
port: 8000
