apiVersion: v1
kind: Service
metadata:
  name: auth-stable
spec:
  type: ClusterIP
  selector:
    app: auth-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-canary
spec:
  type: ClusterIP
  selector:
    app: auth-app
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}