#Image
image:
  repository: "844586871941.dkr.ecr.us-east-1.amazonaws.com/ecom-ecr"
  tag: "auth-service-a4d516e8947f65cf14dc6e9e6f5b864aa7786e54"
  pullPolicy: IfNotPresent

#Replicas
replicas: 2

#Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

#HPA
hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPU: 70

#Non-sensitive config
config:
  dbName: "auth_db"
  algorithm: "HS256"
  accessTokenExpireMinutes: "30"
  


#Service account
serviceAccountName: backend-sa


#Port
port: 8000
