#Image
image:
  repository: "844586871941.dkr.ecr.us-east-1.amazonaws.com/ecom-ecr"
  tag: "frontend-c5a554f759b25945821689e93090e2ec27fe9ca0"
  pullPolicy: IfNotPresent


#Replicas
replicas: 2


#Resources
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

    
#Non-sensitive config
config:
  productServiceUrl: "k8s-default-albingre-7762a7ee01-516050810.us-east-1.elb.amazonaws.com"
  

#Service account
serviceAccountName: backend-sa