#Image
image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent


#Replicas
replicas: 2


#Resources
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

    
#Non-sensitive config
config:
  productServiceUrl: ""
  stripePublishableKey: ""