#Image
image:
  repository: "844586871941.dkr.ecr.us-east-1.amazonaws.com/ecom-ecr"
  tag: "frontend-f96c96ebfbd91cf210b49b7c2713afdaab9dcfd6"
  pullPolicy: IfNotPresent


#Replicas
replicas: 2


#Resources
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

    
#Non-sensitive config
config:
  productServiceUrl: "k8s-default-albingre-7762a7ee01-195082062.us-east-1.elb.amazonaws.com"
  stripePublishableKey: ""

#Service account
serviceAccountName: backend-sa